services:
  - type: web
    name: pharmacy-system
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
